services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:7.0
    container_name: tyba_prueba_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: tyba_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - tyba_prueba_network

  # Aplicacion de Node
  app:
    build: .
    container_name: pruebaTyba
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/tyba_db?authSource=admin
      - DB_NAME=tyba_db
      - PORT=3000
      - GOOGLE_MAPS_API_KEY=AIzaSyD8oulOzAbzu9QsIKVs2X61H17HEpT6uZs
      - SESSION_SECRET=secret_key
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - tyba_prueba_network

volumes:
  mongodb_data:

networks:
  tyba_prueba_network:
    driver: bridge 